name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  create-envfile:
 
    runs-on: self-hosted
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.2
      with:
        envkey_DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        envkey_TWITTER_BEARER: ${{ secrets.TWITTER_BEARER }}
        envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
        directory: "/home/tweetcord/bot_github/bot/bot/"
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.6]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    
    - run: rm -rf dist && tsc
