name: GitHub Actions Demo
on: push
jobs:
  clear:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hexrabbit/whitespace-lint@v0.0.1
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
